# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  configure:
    cmds:
      - >
        cmake
        -B build
        -G "Ninja Multi-Config"
        -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
        .
    env:
      CXX: clang++
      CMAKE_POLICY_VERSION_MINIMUM: 3.5 # 兼容 antlr4
      CMAKE_EXPORT_COMPILE_COMMANDS: ON # clangd 支持

  build:
    deps:
      - configure
    cmds:
      - cmake --build build

  build:release:
    deps:
      - configure
    cmds:
      - cmake --build build --config Release
      - strip build/Release/mioyi-lang
